name: Reverse
on: [workflow_dispatch]

jobs:
  job_reverse:
    runs-on: ubuntu-latest
    name: 'Job reverse'
    steps:
      - name: 'Invoke js action, reverse'
        id: reverse
        uses: vgeorge-fi/js-actions-reverse@v1.0.2
        with:
          text: 'Vineeth Jacob George'

      - name: 'Gets output'
        run: |
            echo 
            echo 'Input:: ${{ steps.reverse.outputs.text }}'
            echo 'Output:: ${{ steps.reverse.outputs.reverse }}'