name: reverse
on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: reverse
        uses: vgeorge-fi/js-actions-reverse@v1.0.0
        with:
          text: 'VINEETH JACOB GEORGE'
      # Use the output from the `hello` step
      - name: Get the output time
        run: |
            echo "Input':' ${{ steps.reverse.outputs.text }}"
            echo "Input ${{ steps.reverse.outputs.text }}"