name: Reverse - workflow
on: [workflow_dispatch]

jobs:
  reverse-job:
    runs-on: ubuntu-latest
    name: 'Reverse - job'
    steps:
      - name: 'Invoke js action, reverse'
        id: reverse
        uses: vgeorge-fi/js-actions-reverse@v1.0.6
        with:
          text: 'Vineeth Jacob George'

      - name: 'Gets output'
        run: |
            echo 
            echo ' Input: ${{ steps.reverse.outputs.input }}'
            echo 'Output: ${{ steps.reverse.outputs.reverse }}'