name: Reverse
on: [workflow_dispatch]

jobs:
  job_reverse:
    runs-on: ubuntu-latest
    name: 'Job reverse'
    steps:
      - name: 'Invoke js action, reverse'
        id: reverse
        uses: vgeorge-fi/js-actions-reverse@v1.0.1
        with:
          who-to-greet: 'VINEETH JACOB GEORGE'

      - name: 'Gets output '
        run: echo "Input ${{ steps.reverse.outputs.reverse }}"